### ISSUE TITLE
Не оправданная лесенка

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#10]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/board.h#L209-L217

Обычно делают так

if (used[i][j]) continue;
if (num != 0) {
num --;
continue;
}

остаток кода про если num == 0

**Comment by veschii0nevstrui** [comment]
Fixed. Чекай в ближайшем коммите.
