### ISSUE TITLE
Вынести строку в отдельную переменную?

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#13]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/cells.h#L50

Хотя впринципи не так уж и важно, чисто для фэншуя

**Comment by veschii0nevstrui** [comment]
Зачем выносить строку, которая нужна только в одном месте в отдельную переменную?
