### ISSUE TITLE
Желательно завести какойнить enum

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#14]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/cells.h#L75

что бы писать не "treasre"
а
Treasure

тогда если ты ошибёшлся и пропустишь u где нибудь
компилятор тебе об этом скажет
и тебе 
не прийдётся дебагать 

Клёва, да?))

**Comment by veschii0nevstrui** [comment]
Solve
