### ISSUE TITLE
Куча констант

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#15]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/cells.h#L93-L103

Лучше всего вынести куданибудь
что бы когда ты решишь что то поменять
зделать это быстро и сразу

а не долго искать по всему файлу

**Comment by veschii0nevstrui** [comment]
Solve for class names. For messages it is useless
