### ISSUE TITLE
Отдельная функция

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#20]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/game.h#L67

рандомное число от 0 до n
ну
я бы написал функцию, вроде полезно

тем боле ты там её 10 раз вызываешь ниже)))))

**Comment by veschii0nevstrui** [comment]
Solve
