### ISSUE TITLE
Ничего не понятно

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#21]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/point.h#L37

либо обьяснить в коментарии
либо отдельная функция

**Comment by veschii0nevstrui** [comment]
Смотри название функции и условный оператор сверху. Мне кажется, что из названия "set_bit" и проверки, что "b == 0" следует, что это строчка устанавливает i-й бит нулём. Выносить в отдельную функцию смысла не вижу, потому что функция "set_bit" и есть вынос этой строчки в отдельную функцию.
