### ISSUE TITLE
спрятать куданибудь

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#3]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/board.h#L17

например в конструктор класса ...

Вообщем, что нибудь придумать что бы это не торчало сверху - кажется это не разумно

**Comment by veschii0nevstrui** [comment]
Переместил в point.h. Вообще говоря, у меня в этом файле валяется всякий мусор, надо как-нибудь по другому файл назвать
