### ISSUE TITLE
Друзья?

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#5]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/board.h#L112

Мне говрили то друзья это плохо((

Ну МБ зедсь без них не обойтись...

**Comment by veschii0nevstrui** [comment]
Я в какой-то момент не понял, как перегрузить оператор [][] (чтобы обращаться напрямую к ячейке). По сути, эта дружба нужна именно для прямого обращения к ячейке. Когда-нибудь переделаю.

**Comment by nevstruevdmitriy** [comment]
operator [] (int a, int b) {}
не получилось?

Я просто то же не шарю))
Мб ещё
operator [][] (int a, int b) {}

**Comment by nevstruevdmitriy** [comment]
А вообще можно написать функцию

getCell(int a, int b) const {}

которая как раз это и возвращет

**Comment by veschii0nevstrui** [comment]
getCell не хочу, слишком громоздко получится. Как перегружу оператор [] - закрою)

**Comment by nevstruevdmitriy** [comment]
А если у тебя вектор векторов
то возвращать operator [] просто const vector<> & кажется решит пробелмму автоматически

**Comment by veschii0nevstrui** [comment]
Поправил. Чекай ближайший коммит.
