### ISSUE TITLE
Дикие константы

### ISSUE THREAD

**Issue by nevstruevdmitriy** [veschii0nevstrui/labyrinth#7]
https://github.com/veschii0nevstrui/labyrinth/blob/2688fcfffe3a3942675afa57b4fdc8a3f8fb9013/board.h#L70-L71

Выниси их куданибудь. Вообще 0 понимания что это))

**Comment by veschii0nevstrui** [comment]
Это escape последовательности. Нужны, чтобы клетки были синие/зелёные/оранжевые. В принципе, нигде больше не нужны, кроме этого места, поэтому оставил здесь. Когда сделаем нормальный фронт с запуском в браузере, эту штуку вообще уберём.

**Comment by nevstruevdmitriy** [comment]
а ок
но всё равно)
